const express = require('express')
const router = express.Router()
const CategoryRoutes = require('./category.route')
const ManufactureRoutes = require('./manufacture.route')
const ProductRoutes = require('./product.route')
const AuthRoutes = require('./auth.route')
const CartRoutes = require('./cart.route')
const CartItemRoutes = require('./cartItem.route')
const PaymentRoutes = require('./payment.route')
const BillRoutes = require('./bill.route')
const BillDetailRoutes = require('./billDetail.route')
const UserRoute = require('./user.route')
const StatisticRoutes = require('./statistic.route')
const InvoiceRoutes = require('./invoice.route')

router.use('/auth', AuthRoutes)
router.use('/category', CategoryRoutes)
router.use('/manufacture', ManufactureRoutes)
router.use('/product', ProductRoutes)
router.use('/cart', CartRoutes)
router.use('/cartItem', CartItemRoutes)
router.use('/payment', PaymentRoutes)
router.use('/bill', BillRoutes)
router.use('/billDetail', BillDetailRoutes)
router.use('/user', UserRoute)
router.use('/statistic', StatisticRoutes)
router.use('/invoice', InvoiceRoutes)

module.exports = router
